// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4pmGgNWbVyNBATJgxp64VrK0zNxvJjl4',
    appId: '1:77913463263:web:ae56535a2b153533c58c6a',
    messagingSenderId: '77913463263',
    projectId: 'proidtest-3e9d5',
    authDomain: 'proidtest-3e9d5.firebaseapp.com',
    storageBucket: 'proidtest-3e9d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5NRsoEnLKyh5A-IOZZuAurXwy3KhWJLc',
    appId: '1:77913463263:android:e72b8a501680d445c58c6a',
    messagingSenderId: '77913463263',
    projectId: 'proidtest-3e9d5',
    storageBucket: 'proidtest-3e9d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHMh7EaLoDmYQa0MmlIa1ZDFm0msxCO6w',
    appId: '1:77913463263:ios:174f1e70e94c92b3c58c6a',
    messagingSenderId: '77913463263',
    projectId: 'proidtest-3e9d5',
    storageBucket: 'proidtest-3e9d5.firebasestorage.app',
    iosBundleId: 'com.example.proidtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHMh7EaLoDmYQa0MmlIa1ZDFm0msxCO6w',
    appId: '1:77913463263:ios:174f1e70e94c92b3c58c6a',
    messagingSenderId: '77913463263',
    projectId: 'proidtest-3e9d5',
    storageBucket: 'proidtest-3e9d5.firebasestorage.app',
    iosBundleId: 'com.example.proidtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4pmGgNWbVyNBATJgxp64VrK0zNxvJjl4',
    appId: '1:77913463263:web:a7c8faedaeb76c24c58c6a',
    messagingSenderId: '77913463263',
    projectId: 'proidtest-3e9d5',
    authDomain: 'proidtest-3e9d5.firebaseapp.com',
    storageBucket: 'proidtest-3e9d5.firebasestorage.app',
  );
}
